name: Deploy to aukus.fun

on:
  workflow_call:
    secrets:
      host:
        description: "Host for SSH"
      username:
        description: "Username for SSH"
      password:
        description: "Password for SSH"
      port:
        description: "Port for SSH"
      webhook_url:
        description: "Discord webhook URL"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          port: ${{ secrets.port }}
          source: './dist/'
          target: '/home/aukus/deploy/frontend/2025/deploy_build'

      - name: swap build and restart nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          port: ${{ secrets.port }}
          command_timeout: 1m
          script: cd "/home/aukus/deploy/frontend/2025" && rm -rf build && mkdir build && mv deploy_build/dist/* ./build/ && rm -r deploy_build/dist

      - name: Aukus v2025 prod frontend build and upload success!
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Aukus v2025 prod frontend deploy to aukus.fun success!
          webhookUrl: ${{ secrets.webhook_url }}

      - name: Aukus v2025 prod frontend build and upload failure!
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Aukus v2025 prod frontend deploy to aukus.fun failure!
          webhookUrl: ${{ secrets.webhook_url }}
